(set-default 'auto-mode-alist
             (append '(("\\.org$" . org-mode)
                       ("\\.asd$" . lisp-mode)
                       ("\\.clj$" . clojure-mode)
                       ("\\.ml[iyl]?$" . tuareg-mode)
                       ("\\.topml$" . tuareg-mode)
                       (".factor" . factor-mode)
                       ("\\.hs$" . haskell-mode)
                       ("\\.lhs$" . literate-haskell-mode)
                       ("\\.py$" . python-mode)
                       ("\\.py\\'" . python-mode)
                       (".stumpwmrc" . lisp-mode)
                       ("\\README$" . text-mode)
                       ("\\TODO$" . text-mode)
                       )
                     auto-mode-alist))
