(defvar bsb/vinyl-collection
  ;; Ambient
  '((:artist "36" :album "Symmetry Systems" :genre "Ambient" :label "Past Inside the Present")
    (:artist "Amble" :album "Drip" :genre "Ambient" :label "Repeatle")
    (:artist "Aphex Twin" :album "Selected Ambient Works" :genre "Ambient" :label "Warp")
    (:artist "Arovane" :album "Tides" :genre "Ambient" :label "Keplar")
    (:artist "Barker" :album "Debiasing" :genre "Ambient" :label "Ostgut Ton")
    (:artist "Barker" :album "Utility" :genre "Ambient" :label "Ostgut Ton")
    (:artist "Barker" :album "BARKER001" :genre "Ambient" :label "Ostgut Ton")
    (:artist "Barker" :album "BARKER002" :genre "Ambient" :label "Ostgut Ton")
    (:artist "Boards of Canada" :album "Geogaddi" :genre "Ambient" :label "Warp")
    (:artist "Daniel Avery + Alessandro Cortini" :album "Illusion of Time" :genre "Ambient" :label "Mute Records")
    (:artist "Dialog" :album "Dialog" :genre "Ambient" :label "Astral Industries")
    (:artist "Future Sound of London" :album "Lifeforms" :genre "Ambient" :label "Universal Music")
    (:artist "JakoJako" :album "Lux" :genre "Ambient" :label "Leisure System")
    (:artist "JakoJako" :album "Metamorphose" :genre "Ambient" :label "Bigamo")
    (:artist "JakoJako & Rodhad" :album "In Vere" :genre "Ambient" :label "WSNWG")
    (:artist "Skee Mask" :album "ISS006" :genre "Ambient" :label "Ilian Tape")
    (:artist "Sky H1" :album "Azure" :genre "Ambient" :label "AD 93")
    (:artist "Sonmi451" :album "Nachtmuziek" :genre "Ambient" :label "Astral Industries")
    (:artist "Tycho" :album "Dive" :genre "Ambient" :label "Ghostly")
    ;; Dub
    (:artist "Andy Stott" :album "Luxury Problems" :genre "Dub" :label "Modern Love")
    (:artist "Deepchord" :album "Lanterns" :genre "Dub" :label "Astral Industries")
    (:artist "Deepchord" :album "Aurotones" :genre "Dub" :label "Soma")
    (:artist "Deepchord" :album "Immersions" :genre "Dub" :label "Astral Industries")
    (:artist "Forest Drive West" :album "Dualism" :genre "Dub" :label "Livity Sound")
    (:artist "Forest Drive West" :album "Recursion" :genre "Dub" :label "Echocord")
    (:artist "Juan Atkins & Moritz Von Oswald" :album "Transport" :genre "Dub" :label "Tresor")
    (:artist "natural/electronic.system" :album "Mythos" :genre "Dub" :label "Midgar")
    (:artist "Porter Ricks" :album "Biokinetics" :genre "Dub" :label "Mille Plateaux")
    (:artist "Topdown Dialectic" :album "S/T 2013" :genre "Dub" :label "Peak Oil")
    (:artist "Topdown Dialectic" :album "Vol 1" :genre "Dub" :label "Peak Oil")
    (:artist "Topdown Dialectic" :album "Vol 2" :genre "Dub" :label "Peak Oil")
    (:artist "Voices from the Lake" :album "Voices from the Lake" :genre "Dub" :label "Prologue")
    (:artist "Vril" :album "Anima Mundi" :genre "Dub" :label "Delsin")
    (:artist "Vril & Rodhad" :album "Out of Place Artefacts" :genre "Dub" :label "WSNWG")
    (:artist "Vril & Rodhad" :album "Out of Place Artefacts II" :genre "Dub" :label "WSNWG")
    ;; Experimental
    (:artist "Amon Tobin" :album "Bricolage" :genre "Experimental" :label "Ninja Tune")
    (:artist "Amon Tobin" :album "Permutation" :genre "Experimental" :label "Ninja Tune")
    (:artist "Amon Tobin" :album "Supermodified" :genre "Experimental" :label "Ninja Tune")
    (:artist "Amon Tobin" :album "Out from Out Where" :genre "Experimental" :label "Ninja Tune")
    (:artist "Beatrice Dillon" :album "Workaround" :genre "Experimental" :label "PAN")
    (:artist "Call Super" :album "Suzi Ecto" :genre "Experimental" :label "Houndstooth")
    (:artist "Call Super" :album "Arpo" :genre "Experimental" :label "Houndstooth")
    (:artist "Fennesz" :album "Endless Summer" :genre "Experimental" :label "Editions Mego")
    (:artist "Jan Jelinek" :album "Loop-finding-jazz-records" :genre "Experimental" :label "Faitiche")
    (:artist "Max Richter" :album "The Blue Notebooks" :genre "Experimental" :label "Deutsche Grammophon")
    (:artist "Nicolas Jaar" :album "Sirens" :genre "Experimental" :label "Other People")
    (:artist "Nils Frahm" :album "Spaces" :genre "Experimental" :label "Erased Tapes")
    (:artist "Oneohtrix Point Never" :album "Returnal" :genre "Experimental" :label "Editions Mego")
    (:artist "Oval" :album "94diskont." :genre "Experimental" :label "Mille Plateaux")
    (:artist "Tim Hecker" :album "Harmony in Ultraviolet" :genre "Experimental" :label "Kranky")
    ;; IDM
    (:artist "Aoki Takamasa" :album "RV8" :genre "IDM" :label "Raster-Noton")
    (:artist "Arovane" :album "Atol Scrap" :genre "IDM" :label "Keplar")
    (:artist "Autechre" :album "Tri Repetae" :genre "IDM" :label "Warp")
    (:artist "Autechre" :album "Chiastic Slide" :genre "IDM" :label "Warp")
    (:artist "Autechre" :album "LP5" :genre "IDM" :label "Warp")
    (:artist "Datach'i" :album "Bones" :genre "IDM" :label "Timesig")
    (:artist "Datassette" :album "Sentinel" :genre "IDM" :label "Lapsus Records")
    (:artist "Gacha Bakradze" :album "Obscure Languages" :genre "IDM" :label "Lapsus Records")
    (:artist "Gimmik" :album "Slow Motion Process" :genre "IDM" :label "Lapsus Records")
    (:artist "Kettel" :album "Myam James Part I" :genre "IDM" :label "Lapsus Records")
    (:artist "Kettel" :album "My Dogan" :genre "IDM" :label "Lapsus Records")
    (:artist "Objekt" :album "Objekt #2" :genre "IDM" :label "Objekt")
    (:artist "Objekt" :album "Flatland" :genre "IDM" :label "PAN")
    (:artist "Objekt" :album "Hypnagogia" :genre "IDM" :label "Leisure System")
    (:artist "Paperclip Minimiser" :album "Paperclip Minimiser" :genre "IDM" :label "Peak Oil")
    (:artist "Patricia" :album "Blue Ridge" :genre "IDM" :label "Analogical Force")
    (:artist "Patricia" :album "Less than 7" :genre "IDM" :label "Acid Test")
    (:artist "Plaid" :album "Feorm Falarx" :genre "IDM" :label "Warp")
    (:artist "Roel Funcken" :album "Sapper Morton" :genre "IDM" :label "Analogical Force")
    (:artist "Roel Funcken" :album "Hexavalent" :genre "IDM" :label "Analogical Force")
    (:artist "RTR" :album "Symmetriades" :genre "IDM" :label "Analogical Force")
    (:artist "Shinra" :album "Meteor" :genre "IDM" :label "Analogical Force")
    (:artist "Shinra" :album "Supernova" :genre "IDM" :label "Analogical Force")
    (:artist "Shinra" :album "Vital Heat" :genre "IDM" :label "Analogical Force")
    (:artist "Shinra" :album "Darkroom" :genre "IDM" :label "Craigie Knowes")
    (:artist "Shinra" :album "Surface" :genre "IDM" :label "Analogical Force")
    (:artist "Squarepusher" :album "Feed Me Weird Things" :genre "IDM" :label "Warp")
    (:artist "u-Ziq" :album "Magic Pony Ride" :genre "IDM" :label "Planet Mu")
    (:artist "Venetian Snares" :album "Rossz Csillag Alatt Szuletett" :genre "IDM" :label "Planet Mu")
    ;; Techno
    (:artist "Andrea" :album "Outlines" :genre "Techno" :label "Ilian Tape")
    (:artist "Andrea" :album "Ritorno" :genre "Techno" :label "Ilian Tape")
    (:artist "Aurora Halal" :album "Liquiddity" :genre "Techno" :label "Mutual Dreaming")
    (:artist "Ben Klock" :album "Before One" :genre "Techno" :label "Ostgut Ton")
    (:artist "Burial" :album "Burial" :genre "Techno" :label "Hyperdub")
    (:artist "Burial" :album "Untrue" :genre "Techno" :label "Hyperdub")
    (:artist "Burial" :album "Kindred" :genre "Techno" :label "Hyperdub")
    (:artist "Clark" :album "Clark" :genre "Techno" :label "Warp")
    (:artist "Clark" :album "Superscope" :genre "Techno" :label "Warp")
    (:artist "Com Truise" :album "Galactic Melt" :genre "Techno" :label "Ghostly")
    (:artist "Daniel Avery" :album "Drone Logic" :genre "Techno" :label "Phantasy Sound")
    (:artist "Daniel Avery" :album "Song for Alpha" :genre "Techno" :label "Phantasy Sound")
    (:artist "Daniel Avery" :album "Ultra Truth" :genre "Techno" :label "Phantasy Sound")
    (:artist "Djrum" :album "Broken Glass Arch" :genre "Techno" :label "R&S Records")
    (:artist "Djrum" :album "Portrait in Firewood" :genre "Techno" :label "R&S Records")
    (:artist "Djrum" :album "Hard to Say / Tournesol" :genre "Techno" :label "R&S Records")
    (:artist "Drexciya" :album "Neptune's Lair" :genre "Techno" :label "Tresor")
    (:artist "Drexciya" :album "Harnessed the Storm" :genre "Techno" :label "Tresor")
    (:artist "Earth Trax" :album "LP1" :genre "Techno" :label "Shall Not Fade")
    (:artist "Earth Trax" :album "LP2" :genre "Techno" :label "Shall Not Fade")
    (:artist "Floating Points" :album "J&W Beat" :genre "Techno" :label "Planet Mu")
    (:artist "Floating Points" :album "Shadows" :genre "Techno" :label "Eglo Records")
    (:artist "Floating Points" :album "Elaenia" :genre "Techno" :label "Luaka Bop")
    (:artist "Floating Points" :album "Kuiper" :genre "Techno" :label "Luaka Bop")
    (:artist "Floating Points" :album "Crush" :genre "Techno" :label "Ninja Tune")
    (:artist "Four Tet" :album "Rounds" :genre "Techno" :label "Domino")
    (:artist "Four Tet" :album "There Is Love In You" :genre "Techno" :label "Domino")
    (:artist "Function" :album "Incubation" :genre "Techno" :label "Ostgut Ton")
    (:artist "Function" :album "Existenz" :genre "Techno" :label "Tresor")
    (:artist "Galaxian" :album "Coming Up for Air" :genre "Techno" :label "Ilian Tape")
    (:artist "HVL" :album "Ostati" :genre "Techno" :label "Organic Analogue")
    (:artist "HVL" :album "Rhythmic Sonatas" :genre "Techno" :label "Bassiani")
    (:artist "HVL" :album "Alignment EP" :genre "Techno" :label "Appian Sounds")
    (:artist "HVL" :album "Aura Fossil EP" :genre "Techno" :label "Appian Sounds")
    (:artist "John Tejada" :album "Signs Under Test" :genre "Techno" :label "Kompakt")
    (:artist "Jon Hopkins" :album "Immunity" :genre "Techno" :label "Domino")
    (:artist "Jon Hopkins" :album "Singularity" :genre "Techno" :label "Domino")
    (:artist "Kangding Ray" :album "Solens Arc" :genre "Techno" :label "Raster-Noton")
    (:artist "Kangding Ray" :album "Hyper Opal Mantis" :genre "Techno" :label "Stroboscopic Artefacts")
    (:artist "Kangding Ray" :album "Ultrachroma" :genre "Techno" :label "Ara Records")
    (:artist "Karenn" :album "Music Sounds Better with Shoe" :genre "Techno" :label "Voam")
    (:artist "Kessler" :album "Ambivalent" :genre "Techno" :label "Shall Not Fade")
    (:artist "Leon Vynehall" :album "Music for the Uninvited" :genre "Techno" :label "3024")
    (:artist "Leon Vynehall" :album "Rojus (Designed to Dance)" :genre "Techno" :label "Running Back")
    (:artist "Leon Vynehall" :album "Rare, Forever" :genre "Techno" :label "Ninja Tune")
    (:artist "Lone" :album "Levitate" :genre "Techno" :label "R&S Records")
    (:artist "Machinedrum" :album "Room(s)" :genre "Techno" :label "Planet Mu")
    (:artist "Machinedrum" :album "Vapor City" :genre "Techno" :label "Ninja Tune")
    (:artist "Machinedrum" :album "A View of U" :genre "Techno" :label "Ninja Tune")
    (:artist "Moderat" :album "II" :genre "Techno" :label "Monkeytown Records")
    (:artist "Neon Chambers" :album "One" :genre "Techno" :label "Dekmantel")
    (:artist "Overmono" :album "BMW Track / So U Kno" :genre "Techno" :label "Poly Kicks")
    (:artist "Pearson Sound" :album "Alien Mode EP" :genre "Techno" :label "Hessle Audio")
    (:artist "Prodigy" :album "The Fat of the Land" :genre "Techno" :label "XL Recordings")
    (:artist "Sam McQueen" :album "Dreams in Sepia" :genre "Techno" :label "a.r.t.less")
    (:artist "Shaun Rudiman" :album "Conduit" :genre "Techno" :label "Pittsburgh Tracks")
    (:artist "Shaun Rudiman" :album "Flow State" :genre "Techno" :label "Pittsburgh Tracks")
    (:artist "Shed" :album "Shedding the Past" :genre "Techno" :label "Ostgut Ton")
    (:artist "Shed" :album "The Traveller" :genre "Techno" :label "Ostgut Ton")
    (:artist "Skee Mask" :album "Compro" :genre "Techno" :label "Ilian Tape")
    (:artist "Skee Mask" :album "Pool" :genre "Techno" :label "Ilian Tape")
    (:artist "Skee Mask" :album "ISS007" :genre "Techno" :label "Ilian Tape")
    (:artist "Special Request" :album "Soul Music" :genre "Techno" :label "Houndstooth")
    (:artist "Stenny" :album "Stress Test" :genre "Techno" :label "Ilian Tape")
    (:artist "Stenny" :album "Upsurge" :genre "Techno" :label "Ilian Tape")
    (:artist "Thom Yorke + Four Tet + Burial" :album "Ego / Mirror" :genre "Techno" :label "Text Records")
    (:artist "Thom Yorke + Four Tet + Burial" :album "Her Revolution / His Rope" :genre "Techno" :label "Text Records")
    (:artist "Tobias" :album "1972" :genre "Techno" :label "Ostgut Ton")
    (:artist "Various Artists" :album "Tresor 30" :genre "Techno" :label "Tresor")
    (:artist "Wata Igarashi & Voiski" :album "9719" :genre "Techno" :label "Delsin")
    (:artist "Wata Igarashi" :album "New Dawn" :genre "Techno" :label "Figure 8")
    (:artist "Xyla" :album "Ways" :genre "Techno" :label "Leaving Records")
    ;; Hip Hop
    (:artist "Aesop Rock" :album "Labor Days" :genre "Hip Hop")
    (:artist "A Tribe Called Quest" :album "The Low End Theory" :genre "Hip Hop")
    (:artist "Bibio" :album "Ambivalence Avenue" :genre "Hip Hop")
    (:artist "Flying Lotus" :album "Cosmogramma" :genre "Hip Hop")
    (:artist "Flying Lotus" :album "Until the Quiet Comes" :genre "Hip Hop")
    (:artist "Fugees" :album "The Score" :genre "Hip Hop")
    (:artist "Ghostface Killah" :album "Fishscale" :genre "Hip Hop")
    (:artist "Gorillaz" :album "Demon Dayz" :genre "Hip Hop")
    (:artist "J Dilla" :album "Donuts" :genre "Hip Hop")
    (:artist "JID" :album "Forever Story" :genre "Hip Hop")
    (:artist "Kendrick Lamar" :album "good kid, m.A.A.d City" :genre "Hip Hop")
    (:artist "MF Doom" :album "Operation: Doomsday" :genre "Hip Hop")
    (:artist "Outkast" :album "Aquemini" :genre "Hip Hop")
    (:artist "Teebs" :album "Ardour" :genre "Hip Hop")
    (:artist "The Avalanches" :album "Since I Left You" :genre "Hip Hop")
    ;; Jazz
    (:artist "Bill Evans" :album "The Tokyo Concert" :genre "Jazz")
    (:artist "Bill Evans Trio" :album "Waltz for Debby" :genre "Jazz")
    (:artist "Dave Brubeck Quartet" :album "Time Out" :genre "Jazz")
    (:artist "Fergus McCreadie" :album "Cairn" :genre "Jazz")
    (:artist "Floating Points + Pharaoh Sanders" :album "Promises" :genre "Jazz")
    (:artist "Herbie Hancock" :album "Maiden Voyage" :genre "Jazz")
    (:artist "Jasmine Myra" :album "Horizons" :genre "Jazz")
    (:artist "John Coltrane" :album "Blue Train" :genre "Jazz")
    (:artist "John Coltrane" :album "Live at the Village Vanguard" :genre "Jazz")
    (:artist "Kamasi Washington" :album "Harmony of Difference" :genre "Jazz")
    (:artist "Lee Morgan" :album "The Sidewinder" :genre "Jazz")
    (:artist "Makaya McCraven" :album "In These Times" :genre "Jazz")
    (:artist "Miles Davis" :album "Kind of Blue" :genre "Jazz")
    (:artist "Nala Sinephro" :album "Space 1.8" :genre "Jazz")
    (:artist "Resavoir" :album "Resavoir" :genre "Jazz")
    (:artist "Sam Wilkes" :album "WILKES" :genre "Jazz")
    (:artist "Sam Wilkes + Sam Gendel" :album "Music for Saxophone and Bass Guitar" :genre "Jazz")
    (:artist "Sarah Vaughan + Clifford Brown" :album "Sarah Vaughan + Clifford Brown" :genre "Jazz")
    (:artist "Sonny Rollins" :album "The Bridge" :genre "Jazz")
    (:artist "Sonny Rollins Quartet" :album "Tenor Madness" :genre "Jazz")
    (:artist "The Comet is Coming" :album "Prophecy" :genre "Jazz")
    (:artist "The Comet is Coming" :album "Channel the Spirits" :genre "Jazz")
    (:artist "The Comet is Coming" :album "Death to the Planet" :genre "Jazz")
    (:artist "The Comet is Coming" :album "Hyper-Dimensional Expansion Beam" :genre "Jazz")
    (:artist "Marvin Gaye" :album "What's Going On" :genre "Soul")
    ;; Soundtracks
    (:artist "Lena Raine" :album "Celeste" :genre "Soundtrack")
    (:artist "Paul Haslinger" :album "Halt and Catch Fire" :genre "Soundtrack")
    (:artist "Paul Haslinger" :album "Halt and Catch Fire Volume 2" :genre "Soundtrack")
    (:artist "Christopher Larkin" :album "Hollow Knight" :genre "Soundtrack")
    (:artist "Materia Collective" :album "Hollow Knight Piano Collections" :genre "Soundtrack")
    (:artist "Disasterpeace" :album "Hyper Light Drifter" :genre "Soundtrack")
    (:artist "Disasterpeace" :album "Rise of the Obsidian Interstellar" :genre "Soundtrack")
    (:artist "Floating Points" :album "Late Night Tales" :genre "Mixtape")
    ;; Indie
    (:artist "Air" :album "Premiers Symptomes" :genre "Indie")
    (:artist "Air" :album "Moon Safari" :genre "Indie")
    (:artist "Band of Horses" :album "Everything All the Time" :genre "Indie")
    (:artist "Beach Bunny" :album "Prom Queen" :genre "Indie")
    (:artist "Beach Bunny" :album "Emotional Creature" :genre "Indie")
    (:artist "Broken Social Scene" :album "You Forgot it in People" :genre "Indie")
    (:artist "Built to Spill" :album "Keep it like a Secret" :genre "Indie")
    (:artist "Car Seat Headrest" :album "Teens of Denial" :genre "Indie")
    (:artist "case/lang/veirs" :album "case/lang/veirs" :genre "Indie")
    (:artist "Death Cab for Cutie" :album "Transatlanticism" :genre "Indie")
    (:artist "DIIV" :album "Is the is are" :genre "Indie")
    (:artist "DIIV" :album "Deceiver" :genre "Indie")
    (:artist "Explosions in the Sky" :album "The Earth is not a cold, dead place" :genre "Indie")
    (:artist "Fleet Foxes" :album "Fleet Foxes" :genre "Indie")
    (:artist "Fleet Foxes" :album "Shore" :genre "Indie")
    (:artist "Florist" :album "Emily Alone" :genre "Indie")
    (:artist "Interpol" :album "Turn on the Bright Lights" :genre "Indie")
    (:artist "Iron & Wine" :album "Woman King" :genre "Indie")
    (:artist "Jay Som" :album "Everybody Works" :genre "Indie")
    (:artist "Jay Som" :album "Anak Ko" :genre "Indie")
    (:artist "Japanese Breakfast" :album "Soft Sounds from Another Planet" :genre "Indie")
    (:artist "Japanese Breakfast" :album "Jubilee" :genre "Indie")
    (:artist "Jimmy Eat World" :album "Bleed American" :genre "Indie")
    (:artist "Julien Baker" :album "Sprained Ankle" :genre "Indie")
    (:artist "Laura Veirs" :album "Saltbreakers" :genre "Indie")
    (:artist "Laura Veirs" :album "July Flame" :genre "Indie")
    (:artist "Lucy Dacus" :album "Home Video" :genre "Indie")
    (:artist "Massive Attack" :album "Protection" :genre "Indie")
    (:artist "Massive Attack vs Mad Professor" :album "No Protection" :genre "Indie")
    (:artist "Massive Attack" :album "Mezzanine" :genre "Indie")
    (:artist "Modest Mouse" :album "Good News for People Who Love Bad News" :genre "Indie")
    (:artist "Moses Sumney" :album "Aromanticism" :genre "Indie")
    (:artist "Moses Sumney" :album "Grae" :genre "Indie")
    (:artist "My Bloody Valentine" :album "Loveless" :genre "Indie")
    (:artist "My Bloody Valentine" :album "mbv" :genre "Indie")
    (:artist "Phoebe Bridgers" :album "Punisher" :genre "Indie")
    (:artist "Pinback" :album "Summer in Abaddon" :genre "Indie")
    (:artist "Pinback" :album "Autumn of the Seraphs" :genre "Indie")
    (:artist "Purity Ring" :album "Shrines" :genre "Indie")
    (:artist "Radiohead" :album "OK Computer" :genre "Indie")
    (:artist "Radiohead" :album "Kid A Mnesia" :genre "Indie")
    (:artist "Radiohead" :album "In Rainbows" :genre "Indie")
    (:artist "Real Estate" :album "Days" :genre "Indie")
    (:artist "Snail Mail" :album "Valentine" :genre "Indie")
    (:artist "Soccer Mommy" :album "Clean" :genre "Indie")
    (:artist "Spoon" :album "Girls Can Tell" :genre "Indie")
    (:artist "The Beths" :album "Future Me Hates Me" :genre "Indie")
    (:artist "The Long Winters" :album "Ultimatum" :genre "Indie")
    (:artist "The National" :album "Boxer" :genre "Indie")
    (:artist "The National" :album "High Violet" :genre "Indie")
    (:artist "The Sea & Cake" :album "Oui" :genre "Indie")
    (:artist "The Sea & Cake" :album "One Bedroom" :genre "Indie")
    (:artist "The Sea & Cake" :album "Everybody" :genre "Indie")
    (:artist "The Sea & Cake" :album "Car Alarm" :genre "Indie")
    (:artist "The Sea & Cake" :album "Runner" :genre "Indie")
    (:artist "The Shins" :album "Oh, Inverted World" :genre "Indie")
    (:artist "Tortoise" :album "TNT" :genre "Indie")
    (:artist "Wet Leg" :album "Wet Leg" :genre "Indie")))

(defun bsb/discogs-search (artist album)
  (let* ((token (password-store-get "discogs/kingcons"))
         (auth-header (format "Discogs token=%s" token))
         (url-request-extra-headers `(("Authorization" . ,auth-header)))
         (base-url "https://api.discogs.com/")
         (base-params "?type=release&format=vinyl")
         (params (format "%s&artist=%s&release_title=%s" base-params artist album))
         (request-url (format "%s/database/search?%s" base-url params)))
    (with-current-buffer
        (url-retrieve-synchronously request-url)
      (goto-char (point-min))
      (let ((data (when (re-search-forward "\r?\n\r?\n" nil t)
                    (json-read))))
        (kill-buffer (current-buffer))
        data))))

(defun bsb/show-cover-art (response)
  (cl-labels ((cover-art (x) (cdr (assoc 'cover_image x)))
              (blank-art? (x) (string-match-p "spacer.gif" (cover-art x))))
    (let* ((results (cdr (assoc 'results response)))
           (record (car (seq-remove #'blank-art? results))))
      (if (null record)
          (message "No matching album found!")
        (let ((cover-art-url (cover-art record)))
          (browse-web cover-art-url)
          (message (format "Now Playing: %s" (cdr (assoc 'title record)))))))))

(defun bsb/filter-vinyl (attribute value)
  (let ((results (seq-copy bsb/vinyl-collection)))
    (cl-flet ((match? (plist) (string= (plist-get plist attribute) value)))
      (seq-filter #'match? results))))

(defun bsb/choose-record (attribute value)
  (let ((candidates (bsb/filter-vinyl attribute value)))
    (bsb/show-random-album candidates)))

(defun bsb/show-random-album (candidates)
  (let* ((record (seq-random-elt candidates))
         (artist (plist-get record :artist))
         (album (plist-get record :album))
         (response (bsb/discogs-search artist album)))
    (message "Searching for %s - %s" artist album)
    (bsb/show-cover-art response)))

(defun bsb/gimme-techno ()
  (interactive)
  (bsb/choose-record :genre "Techno"))

(defun bsb/gimme-music (&optional genre)
  (interactive "sWhat genre? ")
  (if genre
      (bsb/choose-record :genre genre)
    (bsb/show-random-album bsb/vinyl-collection)))

(global-set-key (kbd "s-n") 'bsb/gimme-techno)
(global-set-key (kbd "s-m") 'bsb/gimme-music)
